# Generated by Django 4.2.1 on 2024-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$yxBgh7DeRaVqGTbQRkLZJX$J9U9epCdpond6fwtVmjyVMsfCqQmKZ5p8eF+4Xc1rq4=', max_length=128),
        ),
    ]
