# Generated by Django 4.2.1 on 2024-05-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_cliente_password_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$93VHVxtmewRJK8e3uTR2Ja$ky2byZWdUXZSmVQRJf8ozwiaH8nc3q/1+Bhw7GtD+NQ=', max_length=128),
        ),
    ]
