# Generated by Django 5.0.6 on 2024-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_alter_cliente_password_cart_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$ereddtvAgTX43mXkeoD9Wj$YuQlEiPoTr9VNiAeHxnt2CLsOd3mkiCFllDRyRU+3Xg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
