# Generated by Django 5.0.6 on 2024-06-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_alter_cliente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$MfD0SrXuOQtfJ5QaBqvcsQ$MQpTBamc0lit0X1ViJtst/Rh9V8FoSPCjIJbkd1t1NA=', max_length=128),
        ),
    ]
