# Generated by Django 5.0.6 on 2024-07-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_alter_cliente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$M7IGUDCzqhIPYLM6n6hCcY$2EeLvx566mKplW36d4aLRgvKLggQijyw6X4HU+D/qXA=', max_length=128),
        ),
    ]
