# Generated by Django 5.0.7 on 2024-07-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_alter_cliente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$qRI1fbwFJcXcgQk1mVnHdt$ewy/xFvF6P5b4dafF6XinU2+3not8av/eJbzbW7YGhQ=', max_length=128),
        ),
    ]
